services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./apps/web
          target: /app/apps/web
        - action: sync
          path: ./packages
          target: /app/packages
